DELETE http://localhost:8080/ProiectTW/delete/53
Accept: application/json

###
GET http://localhost:8080/ProiectTW/all/Professor
Accept: application/json

###
GET http://localhost:8080/ProiectTW/findById/53
Accept: application/json

###
POST http://localhost:8080/ProiectTW/add
Content-Type: application/json

{
  "firstName": "Mihai",
  "lastName": "Balan",
  "email": "mihaibalan00@e-uvt.com",
  "birthday": "2000-04-14",
  "password": "password",
  "pictureUrl": "https://bootdey.com/img/Content/avatar/avatar3.png",
  "county": "Romania",
  "college": "Faculty of Mathematics and Computer Science",
  "phone": "07658912",
  "studyType": "Bachelor",
  "specialization": "Computer Science",
  "serialNumber": "I2795",
  "tax": "Tax",
  "CNP": "500044123222",
  "CI": "HD 41311",
  "year": "2",
  "gender": "Male",
  "appUserRole": "Admin"
}

###
PUT http://localhost:8080/ProiectTW/update
Content-Type: application/json

{
"firstName": "MihaiEdited",
"lastName": "Balan",
"email": "mihaibalan00@e-uvt.com",
"birthday": "2000-04-14",
"password": "password",
"pictureUrl": "https://bootdey.com/img/Content/avatar/avatar3.png",
"county": "Romania",
"college": "Faculty of Mathematics and Computer Science",
"phone": "07658912",
"studyType": "Bachelor",
"specialization": "Computer Science",
"serialNumber": "I2795",
"tax": "Tax",
"cnp": "500044123222",
"ci": "HD 41311",
"year": "2",
"gender": "Male",
"appUserRole": "Admin"
}

