DELETE http://localhost:8080/ProiectTW/delete/21
Accept: application/json

###
PUT http://localhost:8080/ProiectTW/update
Content-Type: application/json

{"firstName": "MihaiUpdatedx222222222223",
  "lastName": "BalanUpdatedx2222222",
  "email": "mihaibalan00@yahoo.com"
}

###

###
GET http://localhost:8080/ProiectTW/all/Student
Accept: application/json



###
GET http://localhost:8080/ProiectTW/findById/2
Accept: application/json

###
POST http://localhost:8080/ProiectTW/add
Content-Type: application/json

{
  "firstName": "Mihai12",
  "lastName": "Balan12",
  "email": "mihaibalan200@yahoo.com21",
  "birthday": "30/07/2000",
  "password": "password",
  "pictureURL": "https://bootdey.com/img/Content/avatar/avatar6.png",
  "county": "Romania",
  "college": "Faculty of Mathematics and Computer Science",
  "phone": "07658931",
  "studyType": "Bachelor",
  "specialization": "Computer Science",
  "serialNumber": "I272",
  "tax": "Tax",
  "cnp": "50004423423",
  "ci": "XD 43242",
  "year": "1",
  "gender": "Male",
  "appUserRole": "Student"
}

